### Quiz18
จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า  50 และปริ้นออกมา

In [1]:
import numpy as np

In [6]:
Q = np.random.randint(10,101,[5,5])
print(Q , "\n")
print("ค่าที่มากกว่า 5","\n")
for x in range(5) :
    for y in range(5) :
        if Q[x,y] > 50 :
            print(Q[x,y])

[[51 25 60 24 40]
 [37 75 90 61 96]
 [16 95 90 66 56]
 [65 42 19 61 67]
 [39 10 32 71 62]] 

ค่าที่มากกว่า 5 

51
60
75
90
61
96
95
90
66
56
65
61
67
71
62
