In [1]:
import numpy as np

In [2]:
Met = np.arange(1,26).reshape(5,5)
print(Met)
print(type(Met))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
<class 'numpy.ndarray'>


### Quiz13
ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14

In [35]:
# Quiz-13
print(Met[1:3,2:4])

[[ 8  9]
 [13 14]]


### Quiz14
ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

In [37]:
# Quiz-14
print(Met[3,2:5])

[18 19 20]


### Quiz15
ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

In [39]:
# Quiz-15
print(Met[3:5,0:2])

[[16 17]
 [21 22]]


### Quiz16
ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

In [41]:
# Quiz-16
print(Met[2])

[11 12 13 14 15]


### Quiz17
จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

In [3]:
Met = np.arange(1,26).reshape(5,5)
print(Met)
print(type(Met))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
<class 'numpy.ndarray'>
