### Quiz12
จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

In [1]:
import numpy as np

In [7]:
Result = np.random.randint(50,101,[4,4])
print(Result,"\n")

np.transpose(Result)

[[86 51 93 75]
 [99 58 64 80]
 [88 69 54 79]
 [78 87 67 94]] 



array([[86, 99, 88, 78],
       [51, 58, 69, 87],
       [93, 64, 54, 67],
       [75, 80, 79, 94]])